### PR TITLE
Favorites Router

### PR DESCRIPTION
**Pull request by songamugenzi**
### Updated favorites migration/model, Set up /favorites router
[User Story](https://trello.com/c/T9noG7kG/6-release-1-as-a-user-i-want-to-be-able-to-create-an-account-to-be-able-to-save-searches-and-preferences)
[Trello Task](https://trello.com/c/SqjOqglY/31-create-routes)

# Migration
## Favorites
| column | type | description |
| --- | --- | --- |
| id | integer, unique | favorite id |
| email | string, not nullable | the email that the user used to sign up |
| zip_code | integer, default(-1) | zip code of the city the user favorited |
| city | string, default('default') | name of the city the user favorited |
| state | string, default('default') | state of the city the user favorited |

# Model
#### Updated get, insert, and delete functions in favorites model

> #### /INSERT - addFavorite
> - params
>    - favorite 
> - inserts a new row in the favorites table with values [email, zip_code, city/state]

> #### /DELETE - removeFavorite
> - params
>    - email
>    - id
> - finds and removes row with values [email, id] in [email, id] columns
> - returns count of deleted items

# Router
#### Added get, post, and delete routes in favorites router

> #### /POST - /:email
> - params
>    - email
> - body
>    - city/state
>    - zip code
> - adds favorite to list of favorites matching [email]

> #### /DELETE - /:email/:id
> - params
>    - email
>    - id
> - finds and removes favorite matching [email, id]

### CODE REVIEW

**Comment by allyjay317** [comment]
Looks like we forgot to add the exports.down function in our new migration

**Review by allyjay317 — CHANGES_REQUESTED** [review]
Suggeting the addition of a downgrade in our migration as my "review" because I apparently don't know how this works

**Review by songamugenzi — COMMENTED** [review]
Gotcha! Just added the rollback function to favorites migration.

**Review by allyjay317 — APPROVED** [review]
Thanks for the update!

**Review by allyjay317 — APPROVED** [review]

**Review by samir-hub — APPROVED** [review]
Excellent job documenting the schema and endpoints. 
Also, great job keeping the PR atomic. All changes are related to just the Favorites router and model.

**Comment by allyjay317** [comment]
[Favorites Route](https://trello.com/c/BP7TFu91/41-favorites-route)

**Pull request merged**
